### ISSUE TITLE
Crashes when placed in dispensers?

### ISSUE THREAD

**Issue by BrekiTomasson** [alkyaly/Infinity-Water-Bucket#4] opened 2021-08-19 17:02 UTC
Not 100% sure if this is on you or if there's a mod conflict somewhere, but when I place an Infinity-enchanted water bucket inside a dispenser, my game crashes. `latest.log` doesn't give me any hints as to what is causing the crash.

I'm running Minecraft 1.17.1, Fabric 0.38, and the following mods:

	- adorn@2.1.3+1.17.1
	- advdebug@2.3.0
	- alaskanativecraft@1.3.0
	- amecs@1.3.4+mc.1.16.3
	- amecsapi@1.1.4+mc1.16.5
	- appleskin@mc1.17-2.1.3
	- aqupdcaracal@1.17-1.3.1
	- aqupdgrizzly@1.17-1.2.0
	- architectury@2.4.25
	- autoconfig1u@3.2.2
	- autopath@1.4.3
	- axesareweapons@1.3-1.17
	- axolotlitemfix@1.1.1
	- bannerpp@2.0.3+mc.1.17-rc1
	- bclib@0.3.1
	- bebooks@1.2.9
	- bedspreads@1.4.0-1.17
	- beenfo@1.17.1-fabric0.36.1-1.3.2
	- bendy-lib@2.0.3
	- betterbiomeblend@1.17.0-1.2.3-fabric
	- betterdroppeditems@1.3.0-1.17
	- betterend@0.11.0-pre
	- betternether@5.1.3
	- betterpingdisplay@1.1
	- blame@1.17-4.1.0-fabric
	- blue_endless_jankson@1.2.1
	- blur@2.1.0
	- byg@1.1.8-BETA
	- candlestick@1.1.1
	- capes@1.2.0
	- cardinal-components-base@3.1.1
	- cardinal-components-entity@3.1.1
	- caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld@1.2
	- charm@3.3.2
	- clear-skies@1.5.70
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-config2@5.0.37
	- coloredslime@1.2.6
	- colouredmoss@1.2
	- com_electronwill_night-config_core@3.6.2
	- com_electronwill_night-config_toml@3.6.2
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- compressed@1.3.3
	- copbea@1.0.1
	- copperequipment@1.4
	- cotton-config@1.0.0-rc.7
	- cotton-datapack@1.0.7
	- cotton-logging@1.0.0-rc.4
	- croptopia@1.6.0
	- crowdin-translate@1.3+1.17
	- damagetilt@1.17-fabric-0.1.2
	- dankstorage@2.1-1.17.1
	- dark-loading-screen@1.6.7
	- darkness@1.6.74-snapshot
	- defaultsettings@3.0.3
	- dirtnt@1.1-1.17
	- discerning_furnace@1.0.3+MC1.17-1.17.1
	- ducts@1.1.4
	- earthtojavamobs@1.7.1+1.17-pre3
	- emotecraft@2.1-SNAPSHOT-b692f79
	- enchant_giver@1.1.0
	- expandedstorage@7.0.0
	- extragenerators@1.0.6-BETA+1.17
	- fabric@0.38.0+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.3.0+2f75c6ce18
	- fabric-biome-api-v1@3.1.12+3fe74aa118
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.4+2e8bd82f18
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b4463d5
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.3+kotlin.1.5.21
	- fabric-lifecycle-events-v1@1.4.4+a02b4463d5
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+2e8bd82f18
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab6121d5
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b4463d5
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.7.0+2e8bd82f18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.0+3fe74aa118
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab6121d5
	- fabric-transfer-api-v1@1.1.0+3fe74aa118
	- fabricloader@0.11.6
	- fallflyinglib@3.0.0-beta.2
	- fallingleaves@1.7.3+1.17.1
	- fallingtree@2.12.2
	- fasttransferlib@0.5.6
	- fettlol@1.1.2+1.17
	- fiber@0.23.0-2
	- flonters@1.2.1+1.17.1
	- gbfabrictools@1.3.4+1.17
	- geckolib3@3.0.12
	- guardiansgalore@2.0
	- hologram-api@0.2.0+1.17.1
	- holograms@1.3.0+1.17.1
	- horseinfo@0.3.0-1.17
	- horsestatsvanilla@4.1.8
	- illuminations@1.6.3
	- infinitywaterbucket@1.4-mc1.17-fabric
	- inventoryprofilesnext@0.8.6
	- jankson@3.0.1+j1.2.0
	- java@16
	- keepheadnames@1.4-1.17
	- kirin@1.8.7-1.17
	- krypton@0.1.4
	- kyrptconfig@1.1.10-1.17
	- lambdynlights@2.0.2+1.17
	- libblockattributes@0.9.0-pre.2
	- libblockattributes_core@0.9.0-pre.2
	- libblockattributes_fluids@0.9.0-pre.2
	- libblockattributes_items@0.9.0-pre.2
	- libcd@3.0.3+1.16.3
	- libgui@4.1.3+1.17.1
	- libninepatch@1.1.0
	- libzoomer@0.2.1+1.17
	- lifts@1.2-BETA+1.17
	- lightoverlay@6.0.0
	- lithium@0.7.3
	- lovely_snails@1.0.3+1.17
	- mavm@1.0.3a
	- maybe-data@1.0.1-1.17
	- mcda@1.7.6
	- mcdw@3.4.1
	- mcf-easyfeed@1.3.0
	- mdg@1.0.0
	- midashunger@1.4.0
	- minecraft@1.17.1
	- minepkg-companion@0.4.1
	- miskatonicmysteries@0.0.8
	- modmenu@2.0.4
	- moreberries@1.4.2
	- moreblockbricks@1.3.1
	- mostructures@1.3.0-pre1-1.17.1
	- netherchest@2.0
	- notenoughanimations@1.3.0
	- notenoughcrashes@3.4.0+1.17
	- npcvariety@2.1.2
	- okzoomer@5.0.0-beta.2+1.17
	- omega-config@1.0.8
	- org_aperlambda_lambdajcommon@1.8.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.21
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- packet_tweaker@0.2.0-1.17-pre1
	- pandamc_concreteplus@1.9
	- patchouli@1.17-54-FABRIC-SNAPSHOT
	- perfectaccuracy@1.1
	- placeholder-api@1.0.1+1.17
	- playerabilitylib@1.3.0
	- presencefootsteps@r31-1.17-rc1
	- quickshulker@1.2.2-1.17
	- reach-entity-attributes@2.1.1
	- reborncore@5.0.6-beta+build.94
	- repurposed_structures@2.3.1+1.17.1
	- reroll@1.1.0-1.16.4
	- rightclickharvest@1.3.0
	- ring_of_attraction@1.1.13
	- roughlyenoughitems@6.0.268-alpha
	- satin@1.6.1
	- searchlight@1.1.3
	- seasons@1.2.2-BETA+1.17
	- server_translations_api@1.4.5+1.17
	- servertick@1.5
	- shulkerutils@1.0.4-1.17
	- simpletransport@0.0.11-1.17.1
	- simplyimprovedterrain@0.4.0.3-Fabric-1.17
	- slimyfloor@1.17.1-1.2.0
	- spark@1.6.1
	- spawnermod@1.1.2
	- spruceui@3.2.0+1.17
	- static-content@1.0.1-1.16.2
	- staticdata@1.1.2
	- stickyhopper@2.3-1.17-1
	- stoneholm@1.3
	- taxfreelevels@1.2.1
	- team_reborn_energy@0.1.1
	- techreborn@5.0.6-beta+build.94
	- terraform-biome-builder-api-v1@2.0.0
	- terraform-config-api-v1@2.0.0
	- terraform-overworld-biome-extensions-api-v1@2.0.0
	- terraform-surfaces-api-v1@2.0.0
	- terraform-tree-api-v1@2.0.0
	- terraform-wood-api-v1@2.0.2
	- transliterationlib@1.1.0
	- traverse@4.0.0-beta.2
	- trinkets@3.0.2
	- trumpet-skeleton@1.1.4
	- untitledduckmod@0.3.0
	- villagernames@2.0.0
	- voicechat@1.17.1-1.1.7
	- waterdripsound@1.17-0.2.2
	- waystones@2.0.3
	- william-wythers-overhauled-overworld@1.5
	- winged@1.17.1-3.0.0
	- wolveswitharmor@1.6.0-1.17
	- wthit@3.8.1
	- xaerominimap@21.14.1
	- xaeroworldmap@1.16.0

**Comment by ghost** [comment] 2021-08-19 17:11
Could you send the log? I might have an idea

**Comment by BrekiTomasson** [comment] 2021-08-19 17:11
Hmm.. It turns out I can't reproduce it when trying it in a new world, so now I have no idea what might be going on. I'll continue to try to reproduce it and send you the log if/when I do!

**Comment by coolsimulations** [comment] 2022-02-04 14:42
Greetings, I've taken over this mod and just released version 2.0.0 which re-wrote large portions of the mod. Perhaps the issue is, by chance, now fixed. In any case, I'll close this issue but if it ever occurs again I'll re-open it.

**Closed as completed by coolsimulations** 2022-02-04 14:42 UTC
